server:
  port: 8989
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: damai-ai
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    servlet:
      load-on-startup: 1
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
      generator:
        WRITE_NUMBERS_AS_STRINGS: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/damai_ai?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 123456
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            platform: mariadb
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-b54733188a2e4fac82d0db716ef35ddc
      chat:
        options:
          model: qwen-max-latest
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
    deepseek:
      base-url: https://api.deepseek.com
      api-key: sk-2768ebda7eb943ac90297e039603abe4
      chat:
        options:
          model: deepseek-chat
easy-es:
  #默认为true,若为false则认为不启用本框架
  enable: true
  # es的连接地址,必须含端口
  address : 127.0.0.1:9200
  #账号,若无 则可省略此行配置
  username: elastic
  #密码,若无 则可省略此行配置
  password: elastic
  global-config:
    db-config:
      #索引前缀
      index-prefix: damai-
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: status
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement  